AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template to create an RDS DB instance with a DB subnet group and optional Secrets Manager integration"

Parameters:
  DBEngine:
    Type: String
    Description: "Database engine to be used"
    AllowedValues:
      - mysql
      - postgresql
      - mariadb
    Default: mysql

  MySQLVersion:
    Type: String
    Description: "MySQL version"
    AllowedValues:
      - "8.0.35"
      - "5.7.32"
      - "5.6.51"
    Default: "8.0.35"

  PostgreSQLVersion:
    Type: String
    Description: "PostgreSQL versione
    AllowedValues:
      - "13.4"
      - "12.8"
      - "11.13"
    Default: "13.4"

  MariaDBVersion:
    Type: String
    Description: "MariaDB version"
    AllowedValues:
      - "10.5.9"
      - "10.4.18"
      - "10.3.29"
    Default: "10.5.9"

  CredentialMethod:
    Type: String
    Description: "Method to provide database credentials"
    AllowedValues:
      - UsernamePassword
      - SecretsManager
    Default: UsernamePassword

  DBUsername:
    Type: String
    Description: "Master username for the DB instance"
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."
    Default: admin

  DBPassword:
    Type: String
    Description: "Master password for the DB instance"
    MinLength: 8
    NoEcho: true
    Default: P@ssw0rd

  DBInstanceClass:
    Description: "The RDS instance type"
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Select at least 2 private subnets from 2 different Availability Zones"

Conditions:
  UseUsernamePassword: !Equals [!Ref CredentialMethod, "UsernamePassword"]
  UseSecretsManager: !Equals [!Ref CredentialMethod, "SecretsManager"]

  IsMySQL: !Equals [!Ref DBEngine, "mysql"]
  IsPostgreSQL: !Equals [!Ref DBEngine, "postgresql"]
  IsMariaDB: !Equals [!Ref DBEngine, "mariadb"]

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS DB"
      SubnetIds: !Ref SubnetIds

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Condition: UseSecretsManager
    Properties:
      Description: "Credentials for RDS DB instance"
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 16

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: !Ref DBEngine
      EngineVersion: !If
        - IsMySQL
        - !Ref MySQLVersion
        - !If
            - IsPostgreSQL
            - !Ref PostgreSQLVersion
            - !Ref MariaDBVersion
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      PubliclyAccessible: false
      MultiAZ: false
      MasterUsername: !If
        - UseUsernamePassword
        - !Ref DBUsername
        - !Sub "{{resolve:secretsmanager:${DBSecret}::username}}"
      MasterUserPassword: !If
        - UseUsernamePassword
        - !Ref DBPassword
        - !Sub "{{resolve:secretsmanager:${DBSecret}::password}}"
      Tags:
        - Key: Name
          Value: "Prod_RDS_Instance"
